const fs = require('fs');
const path = require('path');

const viewsDir = path.join(__dirname, 'views');
const files = fs.readdirSync(viewsDir).filter(f => f.endsWith('.ejs'));

files.forEach(file => {
  const filePath = path.join(viewsDir, file);
  let content = fs.readFileSync(filePath, 'utf8');

  // Replace nested EJS tags that were generated by previous scripts
  // Pattern: <%= settings.xxx ? settings.xxx.replace(/\\s+/g, '') : '<%= ... %>' %>
  const nestedPattern = /<%=\s*settings\.([a-zA-Z_]+)\s*\?\s*settings\.\1\.replace\(\/\\s\+\/g, ''\)\s*:\s*'([^']*)'\s*%>/g;
  content = content.replace(nestedPattern, (match, key) => {
    // Provide normal fallback value for known keys
    const defaults = {
      phone_number: '+905346943789',
      whatsapp_number: '905346943789',
      email_address: 'info@ronaglass.com.tr',
      address: '2474 Cad 4/1 Şaşmaz, Etimesgut/Ankara'
    };
    const fallback = defaults[key] || '';
    return `<%= settings.${key} ? settings.${key}.replace(/\\s+/g, '') : '${fallback}' %>`;
  });

  // Also clean any double‑escaped <%=%> patterns that may have been left
  content = content.replace(/<%=%>/g, '<%=');
  content = content.replace(/%>%/g, '%>');

  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Cleaned ${file}`);
});
